server:
  port: 18081
spring:
  application:
    name: discovery-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8080
feign:
  sentinel:
    enabled: true